### ISSUE TITLE
Not scared of print

### ISSUE THREAD

**Issue by XavilPergis** [surrsurus/gazelle#1]
For some reason, the DeerCode interpreter is not frightened by things printing. Usually deer are afraid of strange noises and, since a human usually operates a printer, humans.

It would be far more accurate for the code not to run 90% of the time out of being spooked.

**Comment by surrsurus** [comment]
Very true. This has been a while since first proposed but perhaps all print functions instead of the default (deer) function would be potentially scary.

**Comment by surrsurus** [comment]
_Technically,_ as of some of the more recent updates, the deer is the one printing thus not being scared.
